---
apiVersion: v1
data:
  config.json: |-
    {
      "sink": "{{ .Values.config.sink }}"
    }
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  labels:
    app: {{ template "eventrouter.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
    app.kubernetes.io/name: {{ template "eventrouter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
