---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ template "eventrouter.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
    app.kubernetes.io/name: {{ template "eventrouter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: eventrouter
  template:
    metadata:
      labels:
        component: eventrouter
        tier: control-plane-addons
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/eventrouter
          resources:
            limits:
              cpu: 10m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 30Mi
      serviceAccount: {{ .Values.name }}-{{ .Release.Namespace }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.name }}-configmap

