---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "uniqName" . }}"
  labels:
    app: {{ template "eventrouter.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: {{ template "eventrouter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
